### ISSUE TITLE
New version notification appears

### ISSUE THREAD

**Issue by certem** [DamnWidget/sublime-text#27]
Everytime I start the application I get the "New version available. Download now?" notification. When I check I see that I'm already at the latest version available for my distribution.

 # emerge -s sublime-text
  
[ Results for search key : sublime-text ]
Searching...

*  app-editors/sublime-text
      Latest version available: 3083
      Latest version installed: 3083
      Size of files: 7,330 KiB
      Homepage:      http://www.sublimetext.com
      Description:   Sophisticated text editor for code, markup and prose
      License:       Sublime

[ Applications found : 1 ]

**Comment by DamnWidget** [comment]
No its not, the last version is [3103](https://github.com/DamnWidget/sublime-text/blob/master/app-editors/sublime-text/sublime-text-3103.ebuild), did you forget to update your overlays?

**Comment by m4rcu5** [comment]
Hi, the issue is now valid as there has been an new release: `Sublime Text 3, Build 3114`

**Comment by DamnWidget** [comment]
Sorry for the delay, it is updated now
